### ISSUE TITLE
Issue while importing the library

### ISSUE THREAD

**Issue by alejandroperezcosio** [krypton-byte/tiktok-downloader#11]
from tiktok_downloader import snaptik

```
Traceback (most recent call last):
  File "services/tiktok.py", line 2, in <module>
    from tiktok_downloader import snaptik
  File "/Users/ale/.virtualenvs/scrappy-3.6/lib/python3.6/site-packages/tiktok_downloader/__init__.py", line 1, in <module>
    from .snaptik import snaptik
  File "/Users/ale/.virtualenvs/scrappy-3.6/lib/python3.6/site-packages/tiktok_downloader/snaptik.py", line 8, in <module>
    class snaptik(Session):
  File "/Users/ale/.virtualenvs/scrappy-3.6/lib/python3.6/site-packages/tiktok_downloader/snaptik.py", line 24, in snaptik
    def get_media(self)->list[info_videotiktok]:
TypeError: 'type' object is not subscriptable
```

**Comment by krypton-byte** [comment]
use python3.9
