### ISSUE TITLE
error runing ошибка запуска

### ISSUE THREAD

**Issue by naruto120312** [krypton-byte/tiktok-downloader#13]
root@vps17144:~/newtt# python3 main.py 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from tiktok_downloader import snaptik
  File "/usr/local/lib/python3.8/dist-packages/tiktok_downloader/__init__.py", line 1, in <module>
    from .snaptik import snaptik
  File "/usr/local/lib/python3.8/dist-packages/tiktok_downloader/snaptik.py", line 10, in <module>
    class snaptik(Session):
  File "/usr/local/lib/python3.8/dist-packages/tiktok_downloader/snaptik.py", line 34, in snaptik
    def get_media(self) -> list[info_videotiktok]:
TypeError: 'type' object is not subscriptable

**Comment by fforius** [comment]
upgrade your python to 3.9

**Comment by marse11e** [comment]
Traceback (most recent call last): File "main.py", line 6, in from tiktok_downloader import snaptik File "/opt/venv/lib/python3.8/site-packages/tiktok_downloader/init.py", line 1, in from .snaptik import snaptik, Snaptik File "/opt/venv/lib/python3.8/site-packages/tiktok_downloader/snaptik.py", line 10, in class snaptik(Session): File "/opt/venv/lib/python3.8/site-packages/tiktok_downloader/snaptik.py", line 40, in snaptik def get_media(self) -> list[info_videotiktok]: TypeError: 'type' object is not subscriptable
