### ISSUE TITLE
Able to render slideshow videos.

### ISSUE THREAD

**Issue by andrew121410** [krypton-byte/tiktok-downloader#44]
On the website https://snaptik.app if you put a slideshow type "video" in there you are able to hit the "render video" button for it to produce a regular mp4 video.

Is it possible to implement this?

**Comment by krypton-byte** [comment]
check my latest commit
```
videos=snaptik(tiktok_url)
videos[index].get_render().download("regular.mp4")
```

**Comment by andrew121410** [comment]
Will test tomorrow! thank you 🙏

**Comment by andrew121410** [comment]
I get 

```
root@machine1:~# python3.11 -m tiktok_downloader --url THE_TIKTOK_LINK --snaptik --save test.mp4
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/lib/python3.11/dist-packages/tiktok_downloader/__init__.py", line 1, in <module>
    from .snaptik import snaptik, Snaptik
  File "/usr/local/lib/python3.11/dist-packages/tiktok_downloader/snaptik.py", line 7, in <module>
    from .utils import Download, DownloadAsync, Type, extension_to_type
  File "/usr/local/lib/python3.11/dist-packages/tiktok_downloader/utils.py", line 4, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 89, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
root@machine1:~#
```

**Comment by krypton-byte** [comment]
Did you encounter any errors during the installation of dependencies (Pillow)?
```
pip uninstall Pillow
pip install Pillow
```

**Comment by krypton-byte** [comment]
Check my latest commit.

**Comment by andrew121410** [comment]
Yep that works, thank you!!! 🎉
